# Generated by Django 2.0.4 on 2018-04-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='usersbadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='usersbadge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersnotification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='usersnotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UsersBadge',
        ),
        migrations.DeleteModel(
            name='UsersNotification',
        ),
    ]
