# Generated by Django 2.0.2 on 2018-04-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180408_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
