# Generated by Django 2.0.2 on 2018-03-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overboardapp', '0002_auto_20180307_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='related_question',
            new_name='question',
        ),
    ]
