# Generated by Django 2.0.2 on 2018-03-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overboardapp', '0003_auto_20180304_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
