# Generated by Django 2.0.4 on 2018-05-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='question_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
