# Generated by Django 2.0.4 on 2018-05-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20180510_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_type',
            new_name='type',
        ),
    ]
