# Generated by Django 2.0.2 on 2018-05-10 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180427_1126'),
        ('notifications', '0003_auto_20180510_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Question'),
        ),
    ]
