# Generated by Django 2.0.2 on 2018-05-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='content',
            new_name='content_template',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
    ]
