# Generated by Django 2.0.2 on 2018-05-10 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180510_2104'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0008_usersnotification_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationAnsweredQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_date', models.DateTimeField(verbose_name='date received')),
                ('content', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.Notification')),
                ('related_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='usersnotification',
            old_name='content_template',
            new_name='content',
        ),
    ]
