# Generated by Django 2.0.2 on 2018-05-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20180510_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationnewanswer',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='usersnotification',
            name='notification',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
