# Generated by Django 2.0.2 on 2018-05-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_auto_20180511_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersnotification',
            name='related_question',
        ),
    ]
