# Generated by Django 2.0.2 on 2018-05-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_auto_20180517_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersnotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='UsersNotification',
        ),
    ]
